# we are extending everything from tomcat:8.0 image ...
FROM tomcat:8.0
MAINTAINER suraj.t.acharya@sap.com
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY /target/eeapp-0.1.war /usr/local/tomcat/webapps/